import { CaseUpdatedDataModel } from "@/lib/types";

export const caseUpdatedSample: CaseUpdatedDataModel = {
  TemplateName: "CaseUpdatedEmail",
  PriorityChanged: true,
  PreviousPriority: 0,
  StatusChanged: true,
  IsReopened: false,
  PreviousStatusName: "IsNew",
  PreviousStatusDescription: "Case isn't picked up yet",
  ID: "10042",
  TopicName: "test topic name",
  TopicDescription: "test topic description",
  Title: "test case title",
  Description: "test case description",
  CurrentPriority: 1,
  CurrentStatusName: "InProgress",
  CurrentStatusDescription: "Case is in progress",
  Customer: {
    FirstName: "Courtney",
    LastName: "Cormier",
    FullName: "Courtney Cormier",
    Gender: "F",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Courtney_Cormier56@hotmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  AssignedOrganizationUnit: {
    Name: "Quigley Group",
    BackendID: "t26d3glpkb",
    EmailAddress: "Novella90@yahoo.com",
    PhoneNumber: "1-228-210-6231 x637",
    StreetAndHouseNumber: "863 Lueilwitz Camp 23599",
    ZipCodeAndCity: "49896 Port Dasia",
  },
  OriginatingOrganizationUnit: {
    Name: "Hartmann and Little",
    BackendID: "rn1mk6ihng",
    EmailAddress: "Arnoldo.Koelpin3@yahoo.com",
    PhoneNumber: "891-571-5070 x89732",
    StreetAndHouseNumber: "98691 Scot Ferry 55528",
    ZipCodeAndCity: "35519-8654 Goyettechester",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
