import { CaseCreatedDataModel } from "@/lib/types";

export const caseCreatedSample: CaseCreatedDataModel = {
  TemplateName: "CaseCreatedEmail",
  ID: "10042",
  TopicName: "test topic name",
  TopicDescription: "test topic description",
  Title: "test case title",
  Description: "test case description",
  CurrentPriority: 1,
  CurrentStatusName: "test status name",
  CurrentStatusDescription: "test status description",
  Customer: {
    FirstName: "Levi",
    LastName: "Fisher",
    FullName: "Levi Fisher",
    Gender: "F",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Levi70@hotmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  AssignedOrganizationUnit: {
    Name: "Ernser Inc",
    BackendID: "7hr4jhfe2m",
    EmailAddress: "Hildegard75@gmail.com",
    PhoneNumber: "1-235-938-3750 x230",
    StreetAndHouseNumber: "2342 Pouros Burgs 15601",
    ZipCodeAndCity: "33033 Lucasborough",
  },
  OriginatingOrganizationUnit: {
    Name: "White LLC",
    BackendID: "hu0utr2qd1",
    EmailAddress: "Gloria.Paucek@yahoo.com",
    PhoneNumber: "777-396-9075",
    StreetAndHouseNumber: "847 Dan Road 15459",
    ZipCodeAndCity: "43593-8827 Estelbury",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
