import { CaseCreatedDataModel } from "@/lib/types";

export const caseClosedSample: CaseCreatedDataModel = {
  TemplateName: "CaseClosedEmail",
  ID: "10042",
  TopicName: "test topic name",
  TopicDescription: "test topic description",
  Title: "test case title",
  Description: "test case description",
  CurrentPriority: 1,
  CurrentStatusName: "test status name",
  CurrentStatusDescription: "test status description",
  Customer: {
    FirstName: "Katrina",
    LastName: "Smitham",
    FullName: "Katrina Smitham",
    Gender: "O",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Katrina_Smitham37@gmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  AssignedOrganizationUnit: {
    Name: "Kunze, Turner and Jenkins",
    BackendID: "x4i0aeri34",
    EmailAddress: "Savanna.Weber@gmail.com",
    PhoneNumber: "478.627.1684",
    StreetAndHouseNumber: "303 Carroll Circles 88109",
    ZipCodeAndCity: "88411 Heidenreichmouth",
  },
  OriginatingOrganizationUnit: {
    Name: "Price and Turner",
    BackendID: "i0boyzzzyc",
    EmailAddress: "Katharina87@gmail.com",
    PhoneNumber: "236.407.4695 x765",
    StreetAndHouseNumber: "91012 Cole Course 5809",
    ZipCodeAndCity: "65184 Conroyfurt",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
