import { CaseInteractionCreatedDataModel } from "@/lib/types";

export const caseInteractionCreatedSample: CaseInteractionCreatedDataModel = {
  TemplateName: "CaseInteractionCreatedEmail",
  InteractionText: "Thank you for reaching out. We have reviewed your case and are currently looking into the issue. We will keep you updated on any progress.",
  User: {
    FirstName: "Alan",
    LastName: "Gusikowski",
    FullName: "Alan Gusikowski",
    Gender: "M",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Alan.Gusikowski8@gmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  ID: "10042",
  TopicName: "test topic name",
  Title: "test case title",
  Description: "test case description",
  CurrentPriority: 1,
  CurrentStatusName: "test status name",
  Customer: {
    FirstName: "Brent",
    LastName: "Bins",
    FullName: "Brent Bins",
    Gender: "O",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Brent36@gmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  AssignedOrganizationUnit: {
    Name: "Bode, DuBuque and Pfannerstill",
    BackendID: "ql7rw72ng5",
    EmailAddress: "Clay.Haley@gmail.com",
    PhoneNumber: "1-245-249-7565",
    StreetAndHouseNumber: "8729 Jocelyn Via 47641",
    ZipCodeAndCity: "45593-5324 Lueilwitzberg",
  },
  OriginatingOrganizationUnit: {
    Name: "Hettinger and Hirthe",
    BackendID: "83exrb4i4u",
    EmailAddress: "Nickolas_Gerhold@yahoo.com",
    PhoneNumber: "(505) 852-3071 x930",
    StreetAndHouseNumber: "69939 Adrian Cliffs 8782",
    ZipCodeAndCity: "17206-6159 East Jessietown",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
