import { DigitalGiftCardMessageDataModel } from "@/lib/types";

export const digitalGiftCardMessageSample: DigitalGiftCardMessageDataModel = {
  TemplateName: "DigitalGiftCardMessage",
  Amount: 176.74,
  CurrencyID: "EUR",
  Identifiers: {
    OrderID: "152487",
    OrderLineID: "587421",
    AccessToken: "duaieaaooo",
    GiftCardID: "546874",
  },
  Data: {
    Theme: {
      ID: "itaque",
      Name: "possimus",
      Description: "Quae quia fugit harum repellat.",
      LongDescription: "Vitae et qui ut dolore temporibus harum maxime a facilis.",
      ForegroundColor: "blue",
      BackgroundColor: "yellow",
      ImageUrl: "http://jana.org/handcrafted-frozen-ball",
      ImageWidth: 600,
      ImageHeight: 400,
      VideoUrl: "https://houston.net/digital/money-market-account",
    },
    From: "Greg Schaden",
    To: "Yvette Tremblay",
    Text: "Reprehenderit et dolorum quam laboriosam architecto voluptatem eum ab ab delectus officia autem est ut et atque nihil ut et aut perspiciatis accusamus repellat aut.",
    FromEmailAddress: "Greg39@hotmail.com",
    ToEmailAddress: "Yvette2@hotmail.com",
    PhoneNumber: undefined,
    DeliverySchedule: "2026-04-10T05:48:36.2694574Z",
    UpdateUrl: "http://wilber.info/arizona/designer",
    DeliveryMode: undefined,
  },
  Details: {
    GiftCardNumber: "12345678987654321",
    PIN: "5678",
    DateOfPurchase: "2026-04-09T23:42:25.5498513Z",
    DateOfExpiration: "2027-04-09T23:42:25.5498515Z",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
