import { DigitalGiftCardSenderMessageDataModel } from "@/lib/types";

export const digitalGiftCardSenderMessageSample: DigitalGiftCardSenderMessageDataModel = {
  TemplateName: "DigitalGiftCardSenderMessage",
  Amount: 714.07,
  CurrencyID: "EUR",
  Identifiers: {
    OrderID: "152487",
    OrderLineID: "587421",
    AccessToken: "veoeuueuoe",
    GiftCardID: "546874",
  },
  Data: {
    Theme: {
      ID: "explicabo",
      Name: "veritatis",
      Description: "Consequatur rem est quam facere.",
      LongDescription: "Vitae quia et maxime aliquam et harum facere et neque.",
      ForegroundColor: "blue",
      BackgroundColor: "yellow",
      ImageUrl: "http://earlene.org/indexing/infrastructure/plains",
      ImageWidth: 600,
      ImageHeight: 400,
      VideoUrl: "http://robb.name/movies",
    },
    From: "Bethany Feeney",
    To: "Maurice Will",
    Text: "Enim ut rerum repellat sit molestiae voluptates voluptas porro ut est velit facilis atque blanditiis qui id quod et rerum optio quam fugiat corrupti quis.",
    FromEmailAddress: "Bethany_Feeney98@hotmail.com",
    ToEmailAddress: "Maurice20@gmail.com",
    PhoneNumber: undefined,
    DeliverySchedule: "2026-04-10T03:03:37.3538533Z",
    UpdateUrl: "https://alfred.org/group",
    DeliveryMode: undefined,
  },
  Details: {
    GiftCardNumber: "12345678987654321",
    PIN: "5678",
    DateOfPurchase: "2026-04-09T23:46:01.998478Z",
    DateOfExpiration: "2027-04-09T23:46:01.9984785Z",
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
