import { EmployeeCreatedDataModel } from "@/lib/types";

export const employeeCreatedSample: EmployeeCreatedDataModel = {
  TemplateName: "EmployeeCreated",
  Password: "tiaueoeaaa",
  ResetExpiresAt: "2026-04-10T23:43:50.4781205Z",
  PasswordResetToken: "govnf6eqhwwm94rsztx5f53zzti5ih0c",
  User: {
    Salutation: undefined,
    Title: undefined,
    Initials: undefined,
    FirstName: "Laurence",
    LastName: "Gislason",
    FullName: "Laurence Gislason",
    Gender: "F",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Laurence72@hotmail.com",
    Company: {
      Name: "Gleason, Adams and Johnson",
      VatNumber: "89612941",
      RegistrationNumber: "39946605",
    },
  },
  SuiteUrl: "http://emmy.org/port/credit-card-account",
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
