import { EvapayDataModel } from "@/lib/types";

export const evapaySample: EvapayDataModel = {
  TemplateName: "EVAPAY",
  Url: "http://viva.info/plastic/florida/content-based",
  EmailAddress: "Bradley83@hotmail.com",
  IsAnonymous: false,
  Subject: "Eos minima qui.",
  IsReminder: false,
  OrderID: "333",
  Amount: 11.57,
  CurrencyID: "NOK",
  FirstName: "Katrina",
  LastName: "Bode",
  Gender: "F",
  Order: {
    IsRepair: false,
    CurrencyID: "EUR",
    SoldFromOrganizationUnit: {
      Name: "Howe LLC",
      Description: "Grass-roots encompassing access",
      BackendID: "qgdo54f7xe",
      EmailAddress: "Tillman.Rice@gmail.com",
      PhoneNumber: "1-557-713-2979 x79494",
      HouseNumber: "978",
      Address1: "4106 Roosevelt Islands",
      Address2: "Apt. 806",
      ZipCodeAndCity: "38442-0540 West Sigrid",
      State: "MN",
      ZipCode: "38442-0540",
      City: "West Sigrid",
      OpeningHours: [],
    },
    Lines: [
      {
        ID: "405",
        Description: "Handcrafted Metal Pants",
        TotalQuantityToShip: 2,
        UnitPriceInTax: 132.0,
        TotalAmountInTax: 264.0,
        Type: "NormalProduct",
      },
      {
        ID: "409",
        Description: "Rustic Frozen Car",
        TotalQuantityToShip: 3,
        UnitPriceInTax: 15.10,
        TotalAmountInTax: 45.30,
        Type: "NormalProduct",
      },
      {
        ID: "413",
        Description: "Ergonomic Steel Bacon",
        TotalQuantityToShip: 8,
        UnitPriceInTax: 10.90,
        TotalAmountInTax: 87.20,
        Type: "NormalProduct",
      },
    ],
    Totals: {
      SubTotal: 82.64,
      Total: 100.0,
      Discounts: 0.0,
      ShippingCosts: 0.0,
    },
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
