import { MagicLinkDataModel } from "@/lib/types";

export const magicLinkSample: MagicLinkDataModel = {
  TemplateName: "MagicLink",
  FirstName: "Chelsea",
  LastName: "Kautzer",
  Url: "https://waldo.com/representative/cambridgeshire/rubber",
  ManualCode: "RRM73Y",
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
