import { OrderReturnedDataModel } from "@/lib/types";

export const orderReturnedSample: OrderReturnedDataModel = {
  TemplateName: "OrderReturnedConfirmation",
  Order: {
    ID: "699",
    CurrencyID: "EUR",
    TotalAmountInTax: 2571.0,
    ShippingAddress: {
      FirstName: "Nicole",
      LastName: "Dickinson",
      StreetAndHouseNumber: "8509 Yoshiko Springs 25900",
      ZipCodeAndCity: "11028 Zionburgh",
      CountryID: "BR",
    },
    Lines: [],
  },
  ShippedLines: [
    {
      OrderLineID: "906",
      Description: "Intelligent Fresh Bacon",
      QuantityShipped: 10,
      ShipmentDate: "2026-04-12T14:44:49.889Z",
      TrackingCode: "t70sn2ewxd",
    },
    {
      OrderLineID: "938",
      Description: "Fantastic Wooden Chips",
      QuantityShipped: 6,
      ShipmentDate: "2026-04-13T07:49:28.466Z",
      TrackingCode: "0fh5n1yyd3",
    },
    {
      OrderLineID: "946",
      Description: "Handmade Steel Sausages",
      QuantityShipped: 6,
      ShipmentDate: "2026-04-13T11:11:37.269Z",
      TrackingCode: "othz0pk6af",
    },
  ],
  User: {
    FirstName: "Carole",
    LastName: "Reynolds",
    FullName: "Carole Reynolds",
    Gender: "O",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Carole_Reynolds92@gmail.com",
    Company: {
      Name: "Volkman Inc",
      VatNumber: "31730835",
      RegistrationNumber: "39961396",
    },
  },
  CommercialOrganizationUnit: {
    Name: "Mills, Nitzsche and Homenick",
    EmailAddress: "Alba34@gmail.com",
    PhoneNumber: "1-499-737-6884",
    HouseNumber: "0075",
    Address1: "05330 Kolby Trafficway",
    Address2: "Apt. 944",
    ZipCodeAndCity: "52853-8005 East Evalyn",
    StreetAndHouseNumber: "05330 Kolby Trafficway 0075",
    UpcomingOpeningHours: [],
    OpeningHours: [],
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
