import { OrderShippedConfirmationDataModel } from "@/lib/types";

export const orderShippedConfirmationSample: OrderShippedConfirmationDataModel = {
  TemplateName: "OrderShippedConfirmation",
  User: {
    FirstName: "Elena",
    LastName: "Waters",
    FullName: "Elena Waters",
    Gender: "O",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Elena.Waters@hotmail.com",
    Company: {
      Name: "Spinka LLC",
      VatNumber: "46691252",
      RegistrationNumber: "01302472",
    },
  },
  Order: {
    ID: "383",
    CurrencyID: "EUR",
    TotalAmountInTax: 874.60,
    ShippingAddress: {
      FirstName: "Elena",
      LastName: "Waters",
      StreetAndHouseNumber: "3271 Wilber Walk 82",
      ZipCodeAndCity: "99440 Keeleybury",
      CountryID: "NL",
    },
    Lines: [],
  },
  ShippedLines: [
    {
      OrderLineID: "650",
      Description: "Handcrafted Soft Towels",
      QuantityShipped: 4,
      ShipmentDate: "2026-04-22T15:29:58.000Z",
      TrackingCode: "TRACK1A2B3C",
      TrackingLink: undefined,
    },
    {
      OrderLineID: "668",
      Description: "Small Concrete Towels",
      QuantityShipped: 3,
      ShipmentDate: "2026-04-22T20:40:18.000Z",
      TrackingCode: "TRACK2D4E5F",
      TrackingLink: undefined,
    },
  ],
  UnshippedLines: [
    {
      ID: "432",
      ProductID: "4895",
      Description: "Gorgeous Steel Hat",
      CurrencyID: "EUR",
      UnitPriceInTax: 185.84,
      TotalAmountInTax: 371.68,
      TotalQuantityToShip: 2,
    },
    {
      ID: "436",
      ProductID: "8832",
      Description: "Handmade Cotton Shirt",
      CurrencyID: "EUR",
      UnitPriceInTax: 183.08,
      TotalAmountInTax: 549.24,
      TotalQuantityToShip: 6,
    },
  ],
  Tracking: {
    Code: "wnne12dc4z",
    Link: undefined,
  },
  Data: null,
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    BackendID: "fleurop",
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
  },
};
