import { PasswordResetCompletedDataModel } from "@/lib/types";

export const passwordResetCompletedSample: PasswordResetCompletedDataModel = {
  TemplateName: "PasswordResetCompleted",
  User: {
    Salutation: undefined,
    Title: undefined,
    Initials: undefined,
    FirstName: "Darrell",
    LastName: "Baumbach",
    FullName: "Darrell Baumbach",
    Gender: "M",
    SingleSignOnOnly: false,
    AccountType: "Standard",
    EmailAddress: "Darrell.Baumbach@hotmail.com",
    Company: {
      Name: "Gleason, Adams and Johnson",
      VatNumber: "89612941",
      RegistrationNumber: "39946605",
    },
  },
  AssetsUrl: "https://assets.euw.fleurop.test.eva-online.cloud",
  LanguageID: "nl",
  CountryID: "NL",
  TimeZone: "Etc/UTC",
  IsTestEnvironment: true,
  RunningOnWatchtower: false,
  CurrentOrganizationUnit: {
    Name: "fleurop",
    Description: undefined,
    BackendID: "fleurop",
    EmailAddress: undefined,
    PhoneNumber: undefined,
    HouseNumber: undefined,
    Address1: undefined,
    Address2: undefined,
    ZipCodeAndCity: undefined,
    State: undefined,
    ZipCode: undefined,
    City: undefined,
    BankAccount: undefined,
    VatNumber: undefined,
    RegistrationNumber: undefined,
    BranchNumber: undefined,
    Website: undefined,
    BIC: undefined,
    OpeningHours: [
      { Day: 0, Start: "00:00", End: "00:00", Closed: true },
      { Day: 1, Start: "09:00", End: "18:00", Closed: false },
      { Day: 2, Start: "09:00", End: "18:00", Closed: false },
      { Day: 3, Start: "09:00", End: "18:00", Closed: false },
      { Day: 4, Start: "09:00", End: "18:00", Closed: false },
      { Day: 5, Start: "09:00", End: "18:00", Closed: false },
      { Day: 6, Start: "09:00", End: "18:00", Closed: false },
    ],
    CustomFields: undefined,
    CocNumber: undefined,
    StreetAndHouseNumber: undefined,
  },
};
